name: PreviewDeploy

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Deploy staging
      #   uses: amondnet/vercel-action@v19
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      #     alias-domains: pr-{{PR_NUMBER}}-nuxt-ts-app-preview-888.vercel.app
      #     github-comment: true

      - name: Output preview URL
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "pr-{{ PR_NUMBER }}-mytest.vercel.app"
